# Generated by Django 3.1.4 on 2021-01-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201229_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ColorImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='products')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_images', to='store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_images', to='store.product')),
            ],
            options={
                'verbose_name': 'Colored Images',
                'verbose_name_plural': 'Colored Images',
            },
        ),
    ]
