# Generated by Django 3.1.4 on 2020-12-29 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201222_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name_fr',
        ),
    ]
